//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vagetableAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Log = new HashSet<Log>();
        }
    
        public int id { get; set; }
        public int fridge_id { get; set; }

        [DisplayName("食物名稱")]
        [Required(ErrorMessage = "請輸入食物名稱")]
        [StringLength(50, ErrorMessage = "商品名稱不可大於50字元")]
        public string food_name { get; set; }


        [DisplayName("價格")]
        [Range(typeof(int), "1", "99999", ErrorMessage = "價格請介於1-99999")]
        public Nullable<int> price { get; set; }
        public string photo { get; set; }

        [DisplayName("類別")]
        public string type { get; set; }

        [DisplayName("過期日")]
        [DataType(DataType.Date)]
        public System.DateTime expire_date { get; set; }


        [DisplayName("附註事項，非必要，最多五十字")]
        [StringLength(50, ErrorMessage = "最多五十個字")]
        public string comment { get; set; }

        [JsonIgnore]
        public virtual Fridge Fridge { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
    }
}
